apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: EKS
      image: dhananjay03/easycrud:v6
      ports:
        - containerPort: 8080